// Render Handler - Handles both fastrack and accurate modes
// Separate proxy handler for render operations

import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function handleRenderFastrack(action, data) {
  console.log('[Render Handler] handleRenderFastrack called with:', { action, dataKeys: Object.keys(data) });
  const { base64Sketch, base64Material, additionalDetails } = data;
  
  if (!base64Sketch) {
    throw new Error('Missing base64Sketch for render fastrack');
  }

  // Get base prompt from environment variable
  const basePrompt = process.env.RENDER_FASTRACK_KEY;
  
  if (!basePrompt) {
    throw new Error('RENDER_FASTRACK_KEY environment variable is not configured');
  }

  // Use base prompt and append additional details if provided
  let finalPromptText = basePrompt;
  
  if (additionalDetails && additionalDetails.trim()) {
    finalPromptText += ` ${additionalDetails.trim()}`;
    console.log('[Render Handler] Using RENDER_FASTRACK_KEY + additional details, total length:', finalPromptText.length);
    console.log('[Render Handler] Additional details:', additionalDetails.trim());
  } else {
    console.log('[Render Handler] Using RENDER_FASTRACK_KEY only, length:', finalPromptText.length);
  }

  // Clean base64 data
  const cleanBase64 = base64Sketch.replace(/^data:image\/[a-z]+;base64,/, '');
  const cleanMaterialBase64 = base64Material ? base64Material.replace(/^data:image\/[a-z]+;base64,/, '') : null;

  // Return base64 data for direct download (no Supabase needed)
  const downloadData = `data:image/png;base64,${cleanBase64}`;

  // Get the model
  const model = genAI.getGenerativeModel({ 
    model: "gemini-2.5-flash-image-preview" 
  });

  // Generate content (following old geminiService.ts logic)
  const result = await model.generateContent([
    finalPromptText,
    {
      inlineData: {
        mimeType: "image/png",
        data: cleanBase64
      }
    },
    // Add material image if provided
    ...(cleanMaterialBase64 ? [{
      inlineData: {
        mimeType: "image/png",
        data: cleanMaterialBase64
      }
    }] : [])
  ]);

  const response = await result.response;
  
  // Extract the generated image data
  const generatedImage = response.candidates?.[0]?.content?.parts?.find(
    part => part.inlineData && part.inlineData.mimeType?.startsWith('image/')
  );

  if (!generatedImage?.inlineData?.data) {
    throw new Error('No image generated by Gemini API');
  }

  const imageData = generatedImage.inlineData.data;

  // Let AI determine the aspect ratio - don't force any specific dimensions
  // The AI will return whatever aspect ratio it thinks is best for the input
  console.log('[Render Handler] Using AI-determined aspect ratio');

  // Return in format expected by client
  return {
    success: true,
    mode: "Render Model (Gemini)",
    model_used: "gemini-2.5-flash-image-preview",
    output: [{
      type: "image_generation_call",
      result: imageData
    }],
    message: "Fashion render complete using Gemini AI",
    imageDimensions: {
      width: 1024,
      height: 1536,
      aspectRatio: 1024 / 1536
    },
    downloadData: downloadData // Base64 data for direct download
  };
}

export async function handleRenderAccurate(action, data) {
  console.log('[Render Handler] handleRenderAccurate called with:', { action, dataKeys: Object.keys(data) });
  const { base64Sketch, base64Material, additionalDetails } = data;
  
  if (!base64Sketch) {
    throw new Error('Missing base64Sketch for render accurate');
  }

  // For accurate mode, use OpenAI (implement as needed)
  // This is a placeholder - implement actual OpenAI call
  throw new Error('Render accurate mode not implemented yet');
}

export async function handleRenderPro(action, data) {
  console.log('[Render Handler] handleRenderPro called with:', { action, dataKeys: Object.keys(data) });
  const { base64Sketch, base64Material, additionalDetails, userId } = data;
  
  if (!base64Sketch) {
    throw new Error('Missing base64Sketch for render pro');
  }

  if (!userId) {
    throw new Error('Missing userId for render pro');
  }

  // Import Supabase client
  const { createClient } = await import('@supabase/supabase-js');
  const supabaseUrl = 'https://mtflgvphxklyzqmvrdyw.supabase.co';
  const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

  // Clean base64 data
  const cleanBase64 = base64Sketch.replace(/^data:image\/[a-z]+;base64,/, '');
  const imageBuffer = Buffer.from(cleanBase64, 'base64');

  // Upload image to Supabase board-images bucket
  const imageId = `render_pro_${Date.now()}_${Math.random().toString(36).substring(2, 15)}`;
  const imagePath = `temp-images/${imageId}.png`;

  console.log('[Render Pro] Uploading image to Supabase board-images bucket');

  const { data: uploadData, error: uploadError } = await supabase.storage
    .from('board-images')
    .upload(imagePath, imageBuffer, {
      contentType: 'image/png',
      upsert: false
    });

  if (uploadError) {
    throw new Error(`Failed to upload image to Supabase: ${uploadError.message}`);
  }

  // Get public URL for Segmind API
  const { data: publicUrlData } = await supabase.storage
    .from('board-images')
    .getPublicUrl(imagePath);

  if (!publicUrlData?.publicUrl) {
    throw new Error('Failed to get public URL for image');
  }

  console.log('[Render Pro] Image uploaded, calling Segmind API with public URL:', publicUrlData.publicUrl);

  // Test if the public URL is accessible
  try {
    const testResponse = await fetch(publicUrlData.publicUrl, { method: 'HEAD' });
    console.log('[Render Pro] Public URL test response:', testResponse.status);
    if (!testResponse.ok) {
      throw new Error(`Public URL not accessible: ${testResponse.status}`);
    }
  } catch (testError) {
    console.error('[Render Pro] Public URL test failed:', testError);
    throw new Error(`Public URL test failed: ${testError.message}`);
  }

  // Use public URL as per Segmind API documentation
  const segmindRequest = {
    Base64Sketch: publicUrlData.publicUrl, // Send image URL as per API docs
    Additional_Details: additionalDetails || ''
  };

  console.log('[Render Pro] Segmind request payload:', {
    Base64Sketch: publicUrlData.publicUrl,
    Additional_Details: additionalDetails || '',
    requestSize: JSON.stringify(segmindRequest).length
  });

  // Call Segmind API
  const segmindResponse = await fetch('https://api.segmind.com/workflows/68cdb1828ed0001726e0f151-v2', {
    method: 'POST',
    headers: {
      'x-api-key': process.env.SEGMIND_API_KEY,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(segmindRequest)
  });

  if (!segmindResponse.ok) {
    const errorText = await segmindResponse.text();
    console.error('[Render Pro] Segmind API error:', {
      status: segmindResponse.status,
      statusText: segmindResponse.statusText,
      error: errorText
    });
    throw new Error(`Segmind API error: ${segmindResponse.status} - ${errorText}`);
  }

  // Check if response is JSON (error) or image
  const contentType = segmindResponse.headers.get('content-type');
  console.log('[Render Pro] Segmind response content-type:', contentType);
  
  if (contentType && contentType.includes('application/json')) {
    // Response is JSON, likely an error
    const errorData = await segmindResponse.json();
    console.error('[Render Pro] Segmind API returned JSON error:', errorData);
    throw new Error(`Segmind API error: ${JSON.stringify(errorData)}`);
  }
  
  // Segmind API should return image directly, just like video mode
  const segmindImageBuffer = await segmindResponse.arrayBuffer();
  console.log('[Render Pro] Received image from Segmind API:', {
    size: segmindImageBuffer.byteLength,
    contentType: segmindResponse.headers.get('content-type')
  });

  // Convert to base64
  const imageBase64 = Buffer.from(segmindImageBuffer).toString('base64');

  // Cleanup temp image from board-images bucket
  try {
    await supabase.storage
      .from('board-images')
      .remove([imagePath]);
    console.log('[Render Pro] Cleaned up temporary image');
  } catch (cleanupError) {
    console.warn('[Render Pro] Failed to cleanup temporary image:', cleanupError);
  }

  // Return in the same format as other render modes
  return {
    success: true,
    mode: "Render Pro (Segmind)",
    model_used: "segmind-workflow-v2",
    output: [{
      type: "image_generation_call",
      result: imageBase64
    }],
    message: "Fashion render complete using Segmind AI",
    imageDimensions: {
      width: 1024,
      height: 1536,
      aspectRatio: 1024 / 1536
    },
    downloadData: `data:image/png;base64,${cleanBase64}`
  };
}
