// Render Handler - Handles both fastrack and accurate modes
// Separate proxy handler for render operations

import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function handleRenderFastrack(action, data) {
  console.log('[Render Handler] handleRenderFastrack called with:', { action, dataKeys: Object.keys(data) });
  const { base64Sketch, base64Material } = data;
  
  if (!base64Sketch) {
    throw new Error('Missing base64Sketch for render fastrack');
  }

  // Get base prompt from environment variable
  const basePrompt = process.env.RENDER_FASTRACK_KEY;
  
  if (!basePrompt) {
    throw new Error('RENDER_FASTRACK_KEY environment variable is not configured');
  }

  // Use only the base prompt from environment variable
  const finalPromptText = basePrompt;
  
  console.log('[Render Handler] Using RENDER_FASTRACK_KEY prompt, length:', finalPromptText.length);

  // Clean base64 data
  const cleanBase64 = base64Sketch.replace(/^data:image\/[a-z]+;base64,/, '');
  const cleanMaterialBase64 = base64Material ? base64Material.replace(/^data:image\/[a-z]+;base64,/, '') : null;

  // Auto-download what's being sent to AI (bounding box image)
  let downloadUrl = null;
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `render-input-${timestamp}.png`;
    
    // Convert base64 to buffer
    const imageBuffer = Buffer.from(cleanBase64, 'base64');
    
    // Upload to Supabase temp storage for auto-download
    const tempPath = `temp-downloads/${filename}`;
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('temp-images')
      .upload(tempPath, imageBuffer, {
        contentType: 'image/png',
        upsert: false
      });

    if (!uploadError) {
      // Get public URL for download
      const { data: urlData } = supabase.storage
        .from('temp-images')
        .getPublicUrl(tempPath);
      
      downloadUrl = urlData.publicUrl;
      console.log('[Render Handler] Auto-download URL for bounding box image:', downloadUrl);
      console.log('[Render Handler] Filename:', filename);
    } else {
      console.warn('[Render Handler] Failed to upload for auto-download:', uploadError.message);
    }
  } catch (downloadError) {
    console.warn('[Render Handler] Auto-download setup failed:', downloadError.message);
  }

  // Get the model
  const model = genAI.getGenerativeModel({ 
    model: "gemini-2.5-flash-image-preview" 
  });

  // Generate content (following old geminiService.ts logic)
  const result = await model.generateContent([
    finalPromptText,
    {
      inlineData: {
        mimeType: "image/png",
        data: cleanBase64
      }
    },
    // Add material image if provided
    ...(cleanMaterialBase64 ? [{
      inlineData: {
        mimeType: "image/png",
        data: cleanMaterialBase64
      }
    }] : [])
  ]);

  const response = await result.response;
  
  // Extract the generated image data
  const generatedImage = response.candidates?.[0]?.content?.parts?.find(
    part => part.inlineData && part.inlineData.mimeType?.startsWith('image/')
  );

  if (!generatedImage?.inlineData?.data) {
    throw new Error('No image generated by Gemini API');
  }

  const imageData = generatedImage.inlineData.data;

  // Return in format expected by client
  return {
    success: true,
    mode: "Render Fastrack",
    model_used: "render-ai-v2",
    output: [{
      type: "image_generation_call",
      result: imageData
    }],
    message: "Fashion render complete",
    imageDimensions: {
      width: 1024,
      height: 1536,
      aspectRatio: 1024 / 1536
    },
    downloadUrl: downloadUrl // Auto-download URL for bounding box image
  };
}

export async function handleRenderAccurate(action, data) {
  console.log('[Render Handler] handleRenderAccurate called with:', { action, dataKeys: Object.keys(data) });
  const { base64Sketch, base64Material, additionalDetails } = data;
  
  if (!base64Sketch) {
    throw new Error('Missing base64Sketch for render accurate');
  }

  // For accurate mode, use OpenAI (implement as needed)
  // This is a placeholder - implement actual OpenAI call
  throw new Error('Render accurate mode not implemented yet');
}
