export default async function handler(req, res) {
  console.log('OpenRouter Render AI function called with method:', req.method);
  
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { base64Sketch, promptText, isFastMode = false } = req.body || {};
  const apiKey = process.env.OPENROUTER_API_KEY;
  const siteUrl = process.env.SITE_URL || 'https://coton-creatnet.vercel.app';
  const siteName = process.env.SITE_NAME || 'Coton CreatNet';

  if (!base64Sketch) {
    console.log('Missing required field: base64Sketch');
    return res.status(400).json({ error: 'Missing base64Sketch' });
  }

  if (!apiKey) {
    console.log('Missing OPENROUTER_API_KEY in environment variables');
    return res.status(500).json({ error: 'OpenRouter API key not configured on server.' });
  }

  try {
    console.log('Starting OpenRouter render process...');
    
    // Clean base64 data (remove data:image/png;base64, prefix if present)
    const cleanBase64 = base64Sketch.replace(/^data:image\/[a-z]+;base64,/, '');
    
    // Prepare the prompt
    const enhancedPrompt = promptText 
      ? `Transform this sketch into a photorealistic render. ${promptText}`
      : 'Transform this sketch into a photorealistic render.';
    
    console.log('Making OpenRouter API call with Gemini 2.5 Flash...');

    console.log('Step 1: Analyzing sketch with Gemini 2.5 Flash...');
    
    const geminiResponse = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "HTTP-Referer": siteUrl,
        "X-Title": siteName,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        "model": "google/gemini-2.5-flash-image-preview",
        "messages": [
          {
            "role": "user",
            "content": [
              {
                "type": "text",
                "text": enhancedPrompt + " Provide a detailed description of this sketch for photorealistic image generation, including materials, lighting, colors, and realistic details."
              },
              {
                "type": "image_url",
                "image_url": {
                  "url": `data:image/png;base64,${cleanBase64}`
                }
              }
            ]
          }
        ],
        "temperature": 1,
        "max_tokens": 8192,
        "top_p": 0.95
      })
    });

    if (!geminiResponse.ok) {
      const errorData = await geminiResponse.json();
      console.error('OpenRouter Gemini API error:', errorData);
      return res.status(geminiResponse.status).json({ 
        error: errorData.error || 'Gemini image generation failed',
        details: errorData
      });
    }

    const geminiData = await geminiResponse.json();
    console.log('Gemini response received');
    console.log('=== FULL GEMINI RESPONSE ===');
    console.log(JSON.stringify(geminiData, null, 2));
    console.log('=== END GEMINI RESPONSE ===');

    // Extract generated image from Gemini response
    let generatedImageBase64 = cleanBase64; // Fallback to original sketch
    let description = 'Image processed by Gemini 2.5 Flash';
    
    // Check if Gemini returned an image or description
    if (geminiData.choices?.[0]?.message?.content) {
      const content = geminiData.choices[0].message.content;
      console.log('=== CONTENT ANALYSIS ===');
      console.log('Content type:', typeof content);
      console.log('Content length:', content.length);
      console.log('First 200 chars:', content.substring(0, 200));
      console.log('Contains data:image/:', content.includes('data:image/'));
      console.log('Matches base64 pattern:', !!content.match(/^[A-Za-z0-9+/=]{100,}$/));
      console.log('=== END CONTENT ANALYSIS ===');
      
      // Check if content contains base64 image data
      if (content.includes('data:image/') || content.match(/^[A-Za-z0-9+/=]{100,}$/)) {
        generatedImageBase64 = content.replace(/^data:image\/[a-z]+;base64,/, '');
        console.log('Successfully extracted generated image from Gemini');
        description = 'Photorealistic render generated by Gemini 2.5 Flash';
      } else {
        // If it's text content, use it as description
        description = content;
        console.log('Received text description from Gemini:', description);
      }
    } else {
      console.log('=== NO CONTENT FOUND ===');
      console.log('geminiData.choices exists:', !!geminiData.choices);
      console.log('geminiData.choices length:', geminiData.choices?.length);
      console.log('First choice exists:', !!geminiData.choices?.[0]);
      console.log('Message exists:', !!geminiData.choices?.[0]?.message);
      console.log('Content exists:', !!geminiData.choices?.[0]?.message?.content);
      console.log('=== END NO CONTENT ANALYSIS ===');
    }

    console.log('Gemini processing complete');

    // Return the response in the expected format
    const responseData = {
      success: true,
      model_used: 'google/gemini-2.5-flash-image-preview',
      enhanced_prompt: description,
      original_sketch: cleanBase64,
      output: [{
        type: 'image_generation_call',
        result: generatedImageBase64,
        enhanced_description: description
      }],
      message: 'Render complete using OpenRouter Gemini 2.5 Flash'
    };

    res.status(200).json(responseData);

  } catch (err) {
    console.error('OpenRouter Render AI function error:', err);
    res.status(500).json({ 
      error: err.message || String(err),
      details: 'Internal server error occurred while processing the request'
    });
  }
}
